version: '3'

services:
  cassandra-db:
    container_name: cassandra_db
    image: cassandra_db:4.0
    restart: always
    build:
      context: ./
      dockerfile: Schema.Dockerfile
    ports:
      - "9042:9042"
    expose:
      - "9042"
    network_mode: host # or challenge