apiVersion: apps/v1
kind: Deployment
metadata:
  name: akka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: akka
  template:
    metadata:
      labels:
        app: akka
      name: akka
    spec:
      containers:
        - name: akka
          image: akka:1.0
          #imagePullPolicy: Never  # or IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
  name: akka
spec:
  selector:
    app: akka
  #type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      