apiVersion: apps/v1
kind: StatefulSet # To maintain the database state and its data
metadata:
  name: cassandra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
      name: cassandra
    spec:
      containers:
        - name: cassandra
          image: cassandra_db:4.0
          #imagePullPolicy: Never  # or IfNotPresent
          env:
            - name: USERNAME
              value: "cassandra"
            - name: PASSWORD
              value: "cassandra"
          ports:
            - containerPort: 9042
          volumeMounts:
            - name: cassandra-data
              mountPath: /var/lib/cassandra
      volumes:
        - name: cassandra-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra
spec:
  selector:
    app: cassandra
  ports:
    - protocol: TCP
      port: 9042
      targetPort: 9042

